### ISSUE TITLE
想请教一下，有没有什么可以将创建好的场景以.fbx为文件格式导出的方法？

### ISSUE THREAD

**Issue by XiangdongHe** [mlt131220/ES-3DEditor#10]

**Comment by XiangdongHe** [comment]
楼主您好，感谢您分享的开源项目。
在今天的使用中，我发现将创建好的场景以.obj的格式导出之后，使用Unity打开，所有的三维模型变成一个整体了，但是在Web端他们是互相隔离的。
后来查询资料我发现是因为.obj格式的文件不隔离模型，但是.fbx格式的文件会隔离各个模型，不会把他们当成一个整体。于是我想在`src\utils\menubar\menubar-file.ts`文件中新增导出.fbx文件的方法，但是我发现three.js没有导出.fbx文件的功能，想向您请教一下。

**Comment by mlt131220** [comment]
> 楼主您好，感谢您分享的开源项目。 **问题** 在今天的使用中，我发现将创建好的场景以.obj的格式导出之后，使用Unity打开，所有的三维模型变成一个整体了，但是在Web端他们是互相隔离的。 **思路** 后来查询资料我发现是因为.obj格式的文件不隔离模型，但是.fbx格式的文件会隔离各个模型，不会把他们当成一个整体。于是我想在`src\utils\menubar\menubar-file.ts`文件中新增导出.fbx文件的方法，但是我发现three.js没有导出.fbx文件的功能，想向您请教一下。

我觉得导出为glTF格式会是更好的方案
