### ISSUE TITLE
材质贴图怎么实现贴图的缩放

### ISSUE THREAD

**Issue by sevenen** [mlt131220/ES-3DEditor#12]
材质贴图怎么实现贴图的缩放
比如我画一个地板，我上传的贴图只是一块地板砖的，但是我需要整块地板。
还有就是现有的示例里面所有的物体都在右面材质部分看不到参数，这是为什么
![image](https://github.com/user-attachments/assets/7ce5d21b-6880-48b5-9202-00d49ae9bfbc)

**Comment by mlt131220** [comment]
> 材质贴图怎么实现贴图的缩放 比如我画一个地板，我上传的贴图只是一块地板砖的，但是我需要整块地板。 还有就是现有的示例里面所有的物体都在右面材质部分看不到参数，这是为什么 ![image](https://private-user-images.githubusercontent.com/23046337/361119333-7ce5d21b-6880-48b5-9202-00d49ae9bfbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NjkxNjksIm5iZiI6MTcyNDY2ODg2OSwicGF0aCI6Ii8yMzA0NjMzNy8zNjExMTkzMzMtN2NlNWQyMWItNjg4MC00OGI1LTkyMDItMDBkNDlhZTliZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDEwNDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYzBmZDY5MzJkZWVlYTQ1ZWEyNTA3MzNmZDc2NjU3MTk3N2ZmNWE1ZTJlMDhjNTJiNzk4NDA1MDVmYjMyMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lYdbXlWPJrjBpHgV3doX1oQv7y-rsVM_j7S32ofvTIM)

你好，实在抱歉，在对场景预览模块更新时影响到了场景编辑内的属性查看，现已修复！
同时，针对于你对材质贴图重复平铺的需求，现已增加贴图在UV方向平铺的次数和方式设置。
