### ISSUE TITLE
示例代码没更新吗？

### ISSUE THREAD

**Issue by linrencai** [mlt131220/ES-3DEditor#3]

**Comment by mlt131220** [comment]
> _No description provided._

请问你说的是什么示例？

**Comment by linrencai** [comment]
> > _No description provided._
> 
> 请问你说的是什么示例？

图纸库和工业场景库

**Comment by mlt131220** [comment]
> > > _No description provided._
> > 
> > 
> > 请问你说的是什么示例？
> 
> 图纸库和工业场景库

普通图片和模型，所以去除了。
这两天会更新CAD图纸在线预览关联的功能。
