### ISSUE TITLE
RVT是如何支持的？

### ISSUE THREAD

**Issue by KennanChan** [mlt131220/ES-3DEditor#4]
看到介绍里写了支持RVT，实际使用选择了RVT文件但是提示并不支持呢

**Comment by mlt131220** [comment]
> 看到介绍里写了支持RVT，实际使用选择了RVT文件但是提示并不支持呢

RVT与RVM都是支持的（需要上传并轻量化，并非直接导入），在DEMO网站有BIM分栏，其下是用此Editor轻量化后的BIM文件。
此Editor支持上传Rvt并轻量化回显，但是由于耗费资源，且我的服务器过于便宜不便于拿来支撑，所以Demo站点上传转换功能被我禁用了。
![1711623151827](https://github.com/mlt131220/ES-3DEditor/assets/48863081/c6f0b380-f679-46d9-ad9a-a0dd208e277a)
![image](https://github.com/mlt131220/ES-3DEditor/assets/48863081/59a04a96-972e-4189-b519-380e3f191089)

**Comment by fuuhoo** [comment]
轻量化的后端服务项目地址在哪？是否支持私有化部署测试

**Comment by mlt131220** [comment]
> 轻量化的后端服务项目地址在哪？是否支持私有化部署测试

后端服务和我别的项目后端集成到一起去了，我会尽快抽出时间将其单独抽离并开源。Rvt轻量化使用的主要还是Revit软件二次开发的方式做的。
