### ISSUE TITLE
DWG和DXF格式支持？

### ISSUE THREAD

**Issue by xrui94** [mlt131220/ES-3DEditor#5]
请教一下，DWG和DXF格式都支持吗？还是只支持DXF。另外是怎么支持的呀？也是上传到服务端解析么？

**Comment by mlt131220** [comment]
> 请教一下，DWG和DXF格式都支持吗？还是只支持DXF。另外是怎么支持的呀？也是上传到服务端解析么？

DWG文件在服务端解析为DXF，然后使用ThreeJS按图元类型分别在场景中绘制还原，具体图元属性可以查看[AutoCAD DXF格式](https://documentation.help/AutoCAD-DXF-zh/WSfacf1429558a55de185c428100849a0ab7-5f35.htm)，推荐使用离屏渲染的方式，以免阻塞主线程。

**Comment by xrui94** [comment]
> > 请教一下，DWG和DXF格式都支持吗？还是只支持DXF。另外是怎么支持的呀？也是上传到服务端解析么？
> 
> DWG文件在服务端解析为DXF，然后使用ThreeJS按图元类型分别在场景中绘制还原，具体图元属性可以查看[AutoCAD DXF格式](https://documentation.help/AutoCAD-DXF-zh/WSfacf1429558a55de185c428100849a0ab7-5f35.htm)，推荐使用离屏渲染的方式，以免阻塞主线程。

你用的哪个库来解析的DWG为DXF呀？转换后会不会丢失一些文字、曲线数据啥的？

**Comment by puxiao** [comment]
我想看你怎么实现导入 CAD，结果：
1、package.json 中有 "@dxfom/mtext": "0.3.2"，可是我在代码里并没有找到任何文件使用。
2、我找到了 export function fetchAddDwg2dxf(data) {} 这个函数，但发现竟然是请求API的。
所以究竟你是怎么转换的，还是一个迷。

**Comment by mlt131220** [comment]
> 我想看你怎么实现导入 CAD，结果： 1、package.json 中有 "@dxfom/mtext": "0.3.2"，可是我在代码里并没有找到任何文件使用。 2、我找到了 export function fetchAddDwg2dxf(data) {} 这个函数，但发现竟然是请求API的。 所以究竟你是怎么转换的，还是一个迷。

解析模块只支持了大部分图元，还未支持3DFace之类的图元，我还在持续添加中，所以未上传该部分源码。
具体思路，使用LibreDWG服务将dwg文件转为dxf（fetchAddDwg2dxf这个接口请求就是发起服务端转换的）,然后前端解析dxf（文本方式解析，按行读取）文件，用threejs按不同图元重绘出来。
同时，为了避免cad绘制的场景使主场景卡顿，尽量使用离屏渲染的方式渲染cad。

整个解决过程就是这样的，希望对你有所帮助。产出可以看本项目示例站点左侧下方cad模块。
